SQUARE_VENDORS = [
  'AAA Crafts',
  'Abel Soto Diaz',
  'Amos Goldbaum',
  'Amy Rose Moore',
  'Amy Rose WS',
  'Animal Instincts',
  'Aprile Crochet',
  'Baby Cats',
  'Backerton',
  'Bad Attitude Bunny Illustration',
  'Baja Llama',
  'Bart Bridge',
  'Ben10 Makes',
  'Bernal Burrow',
  'Bored Inc',
  'Brenna Daugherty WS',
  'Callie & Co',
  'Campfires & Coffee',
  'Castro Street Fair',
  'Cat City',
  'Chanamon WS',
  'Charlie Wylie',
  'Chasindoodles',
  'Chronicle Books',
  'Chunky Pineapple',
  'Coffee n Cream Press',
  'Conrad J Camit',
  'Cookie and the Dude',
  'Cosmic Shark Clothing',
  'Crescent Loun',
  'Crimson and Clover',
  'Croptop',
  'Culk',
  'Cuppa Fog',
  'DIRTboy Ceramics',
  'Daily SanFranciscan',
  'Dalix',
  'Dave Marcoullier',
  'Day3DLab',
  'Decore Ate Me',
  'Denise Tarantino',
  'Diamond L Leatherworks',
  'Doodles Ink',
  'Doodles Ink WS',
  'Doug DaSilva',
  'Faiths Aesthetic Jewelry',
  'Fanchromatic Nails',
  'Felt Flanerie',
  'Found Image Press',
  'Frank Vera',
  'GRQP WS',
  'Geometry',
  'Ghetto Goldilocks',
  'Girly',
  'Gneiss Wood',
  'Golden Gate Design',
  'Gooch',
  'Granny Panty Designs',
  'Greater Hood',
  'Green Tree Jewelry',
  'Hamish Thompson',
  'Headline',
  'Heathered',
  'Heavenly Soap Company',
  'Heliotrope',
  'Heliotrope WS',
  'Higa Art',
  'Hilary Williams',
  'Honestly Goods',
  'Hotel Castro',
  'Imose Candle Company',
  'Impressed by Nature',
  'J-Storm Maps',
  'Jeana Hadley',
  'Jeffrey Dal Porto',
  'Jennifer Clifford',
  'Jenny Lemons',
  'John Mavroudis',
  'Jojo Z',
  'Juan Manuel Carmona',
  'Julie Flynn',
  'Karen Chrysiliou',
  'Katy Kristin',
  'Kindred Caramels',
  'Kristina Micotti',
  'LIX PERLE',
  'Lady Alamo WS',
  'Leah Tumerman',
  'Lemonade 51o',
  'Liyana Studio',
  'Local Notion',
  'Local Take',
  'Local Take - 3 Fish Studios',
  'Local Take - Amano',
  'Local Take - Bag',
  'Local Take - Cavallini',
  'Local Take - Frame',
  'Local Take - Gift Certificate',
  'Local Take - Rickshaw',
  'Local Take - Shipping',
  'Local Take - postage',
  'Lucky Bee Press',
  'Maika',
  "Marshall's Farm",
  'Maureen Shields',
  'Melan Made That',
  'Meyer Lemon Crafts',
  'Mildstyles',
  "Mind's Eye Design",
  'Miranda Caroligne',
  'Mission Thread Clothing',
  'Mojo Bakes SF',
  'Mr Rogers',
  'New Skool',
  'Nidhi Chanani',
  'Nina Designs',
  'Nooworks',
  'Noteify',
  'Noteify WS',
  'Nyxa',
  'Ofina',
  'Oodlebadoodle',
  'Ork Inc',
  'Pamela Baron',
  'Papa Llama',
  'Peking Handicraft',
  'Pixelknit',
  'Point Two Design',
  'Pretty Alright Goods',
  'Pretty Fun Designs',
  'Prismatips',
  'Properly Improper',
  'Queer the Way',
  'Rachael Stamps',
  'Rainn',
  'Raymundo Valdez',
  'Render Goods',
  'Roman Ruby Botanicals',
  'Romey Designs',
  'Rover & Kin',
  'SF Candle Co',
  'SF Chocolate Factory',
  'SF Mercantile',
  'SF Mercantile - LT',
  'Salty Alyce',
  'Sebastian Roldan',
  'Sew Mei Mei',
  'Shawn R Harris',
  'Silk Road Bazaar',
  'Sincerely\\, Rob',
  'Sirron Norris',
  'Souvenear',
  'Space46',
  'Spacepig Press',
  'Spicer Bags',
  'Splendid Colors',
  'Steamer Lane Design',
  'Stellercraft',
  'Sticker Horse',
  'Stuart Schuffman',
  'Studio Basho',
  'Studio for Metropolitan Craft',
  'Sundrop Jewelry',
  'Sunshine Studios',
  'Sweet Bippy Press',
  'Swift Retail',
  'TMK Design',
  'The Curious Potter',
  'The GRQP',
  'The Heated',
  'The Peach Fuzz',
  'The Treasurie',
  'Ticket Chocolate',
  'Tickle and Smash',
  'Tiepology',
  'Tommy Breeze',
  'Transatlantic Romance Designs',
  'Trays4Us',
  'Trays4Us WS',
  'Unblushing',
  'Uno Atelier',
  'Unpossible Cuts',
  'Unpossible Cuts WS',
  "Until There's A Cure",
  'Urb Apothecary',
  'Yarrow Goods',
  'Yellow Daisy Paper Co',
  'Yellow Owl Workshop',
  'Yvette Buigues',
  'Zig Zag',
  'not tracked',
]

SHOPIFY_VENDORS = [
  '3 Fish Studios',
  'AAA Crafts',
  'Amano Studio',
  'Amos Goldbaum',
  'Amy Rose Moore',
  'Animal Instincts',
  'Aprile Crochet',
  'Baby Cats',
  'Backerton',
  'Bad Attitude Bunny',
  'Baja Llama',
  'Bart Bridge',
  'Bernal Burrow',
  'Bored Inc.',
  'Brenna Daugherty',
  'Campfires & Coffee',
  'Castro Street Fair',
  'Cat City, Ink',
  'Cavallini',
  'Charlie Wylie',
  'Chronicle Books',
  'Chunky Pineapple',
  'Coffee n Cream Press',
  'Cookie and the Dude',
  'Cosmic Shark Clothing',
  'Crimson and Clover',
  'Culk',
  'Cuppa Fog',
  'Dalix',
  'Doodles Ink',
  'Doug DaSilva',
  'Elizabeth W',
  'Everyday Love',
  'Frank Vera',
  'GRQP',
  'Geometry',
  'Girly',
  'Golden Gate Design',
  'Granny Panty Designs',
  'Green Tree Jewelry',
  'Headline',
  'Heavenly Soap Company',
  'Heliotrope',
  'Higa Art',
  'Hilary Williams',
  'Honestly Goods',
  'Jeana Hadley',
  'Jennifer Clifford',
  'Jenny Lemons',
  'John Mavroudis',
  'Jojo Z',
  'Juan Manuel Carmona',
  'Julia Szendrei',
  'Julie Flynn',
  'Karen Chrysiliou',
  'Katy Kristin',
  'Kindred Caramels',
  'Lady Alamo',
  'Leah Tumerman',
  'Lemonade 51o',
  'Liyana Studio',
  'Local Take',
  'Lucky Bee Press',
  'Made by Chanamon',
  'Maika',
  'Mark Poulin',
  "Marshall's Honey",
  'Maureen Shields',
  'Melan Made That',
  'Mildstyles',
  "Mind's Eye Design",
  'Mission Threads',
  'Mojo Bakes',
  'New Skool',
  'Nina Designs',
  'Nooworks',
  'Noteify',
  'Nyxa',
  'Ofina',
  'Omnivore',
  'Ork',
  'Pamela Baron',
  'Papa Llama',
  'Peking Handicraft',
  'Pin Up Cosmetics',
  'Pixelknit',
  'Point Two Design',
  'Poppy and Quail',
  'Prismatips',
  'Properly Improper',
  'Queer the Way',
  'Rachael Stamps',
  'Raymundo Valdez',
  'Render Goods',
  'Rickshaw Bags',
  'Roman Ruby Botanicals',
  'Rover + Kin',
  'SF Candle Co',
  'SF Chocolate Factory',
  'SF Mercantile',
  'Salty Alyce',
  'San Francycle',
  'Sew Mei Mei',
  'Shawn Ray Harris',
  'Silk Road Bazaar',
  'Sincerely, Rob',
  'Sirron Norris',
  'Space 49',
  'Spacepig Press',
  'Spicer Bags',
  'Splendid Colors',
  'Steamer Lane',
  'Sticker Horse',
  'Studio Basho',
  'Studio for Metropolitan Craft',
  'Sundrop',
  'Sunshine Studios',
  'Sweet Bippy Press',
  'Swift Retail',
  'The Heated',
  'The Matt Butler',
  'The Peach Fuzz',
  'The Treasurie',
  'Ticket Chocolate',
  'Tickle & Smash',
  'Tiepology',
  'Tomoko Maruyama',
  'Trays4Us',
  'Unblushing',
  'Uno Atelier',
  'Unpossible Cuts',
  'Urb Apothecary',
  'Yarrow Goods',
  'Yellow Daisy',
  'Yellow Owl Workshop',
  'Zig Zag',
]
